import { Container, Text } from '@chakra-ui/react'
import Head from 'next/head'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<Container
				maxW='container.xl'
				bg={'twitter.900'}
			>
				<Text>Evently</Text>
			</Container>
		</div>
	)
}
